const profile_categories = [
  // Public / creative profiles
  { name: "Actor" },
  { name: "Actress" },
  { name: "Musician" },
  { name: "Singer" },
  { name: "Songwriter" },
  { name: "Writer" },
  { name: "Director" },
  { name: "Photographer" },
  { name: "Videographer" },
  { name: "Filmmaker" },
  { name: "Designer" },
  { name: "Fashion Designer" },
  { name: "Graphic Designer" },
  { name: "Artist" },
  { name: "Digital Artist" },
  { name: "Illustrator" },
  { name: "Painter" },
  { name: "Model" },
  { name: "Comedian" },
  { name: "Influencer" },
  { name: "Content Creator" },
  { name: "Athlete" },
  { name: "Coach" },
  { name: "Dancer" },
  { name: "Choreographer" },
  { name: "Makeup Artist" },
  { name: "Hair Stylist" },
  { name: "Public Figure" },
  { name: "Producer" },
  { name: "DJ" },
  { name: "Radio Host" },
  { name: "TV Host" },
  { name: "Journalist" },
  { name: "Bblue.ai" },
  { name: "Podcaster" },
  { name: "Entrepreneur" },
  { name: "Chef" },
  { name: "Craftsperson" },
  { name: "Educator" },
  { name: "Scientist" },
  { name: "Activist" },
  { name: "Politician" },
  
  // Business / company profiles
  { name: "Business" },
  { name: "Company" },
  { name: "Organization" },
  { name: "Startup" },
  { name: "Brand" },
  { name: "Non-Profit" },
  { name: "E-commerce Store" },
  { name: "Restaurant" },
  { name: "Cafe" },
  { name: "Retail Store" },
  { name: "Fitness Center" },
  { name: "Salon" },
  { name: "Barbershop" },
  { name: "Spa" },
  { name: "Event Venue" },
  { name: "Marketing Agency" },
  { name: "Consulting Firm" },
  { name: "Tech Company" },
  { name: "Media Company" },
  { name: "Publishing House" },
  { name: "Production Company" },
  { name: "Real Estate Agency" },
  { name: "Travel Agency" },
  { name: "Hotel" },
  { name: "Educational Institution" },
  { name: "Hospital" },
  { name: "Clinic" },
  { name: "Charity" },
  { name: "Government Agency" },
  { name: "Financial Institution" },
  { name: "Law Firm" },
  { name: "Logistics Company" },
  { name: "Construction Company" },
  { name: "Manufacturing Company" },
  { name: "Pharmaceutical Company" }
];
export default profile_categories